

CREATE TABLE CUSTOMER(
    USER_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR2(100),
    LASTNAME VARCHAR2(100),
    USERNAME VARCHAR2(100) NOT NULL,
    PASS_WORD VARCHAR2(100) NOT NULL
);
/

CREATE TABLE ACCOUNTS(
    ACCOUNT_ID INTEGER PRIMARY KEY,
    ACCOUNT_NUMBER INTEGER,
    USER_ID INTEGER NOT NULL,
    BALANCE NUMBER(6,2) DEFAULT 00.00
);

ALTER TABLE ACCOUNTS
ADD CONSTRAINT FK_CUSTOMER_ACCOUNTS
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER(USER_ID);
/
CREATE SEQUENCE SQ_CUSTOMER_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_ACCOUNTS_PK
START WITH 1
INCREMENT BY 1;


